springdoc:
  swagger-ui:
    path: swagger
    try-it-out-enabled: true
    filter: true
    operations-sorter: method
    display-request-duration: true
#    supported-submit-methods: GET, POST, PUT, DELETE, OPTIONS, HEAD, PATCH, TRACE
#    enabled: false
#    query-config-enabled: false
#  api-docs:
#    enabled: false

spring:
  application:
    name: Diplomats

  jackson:
    time-zone: Asia/Seoul

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diplomat?serverTimezone=Asia/Seoul
    username: root
    password: ohw62459930!
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: bXlWZXJ5TG9uZ1NlY3JldEtleVRoYXRJc0F0TGVhc3Q2NEJ5dGVzTG9uZ0ZvckZTNTEyQWxnb3JpdGhtVG9Xb3JrUHJvcGVybHkxMjM0NTY3ODk
    access:
      expiration: 900000
    refresh:
      expiration: 604800000

logging.level:
  org.hibernate.SQL: debug